events {
  worker_connections 1024;
}

http {
  upstream django_backend {
    server django_web:8000;
  }

  upstream flask_ratings {
    server flask_ratings:5000;
  }

  server {
    listen 80;

    location /api/v2/calificaciones {
      proxy_pass http://flask_ratings;
      proxy_set_header Host $host;
    }

    location /health {
      proxy_pass http://flask_ratings;
    }

    location / {
      proxy_pass http://django_backend;
      proxy_set_header Host $host;
    }
  }
}