# Generated by Django 5.2.11 on 2026-03-05 16:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueTiempo',
            fields=[
                ('idBloque', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diaSemana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fechaNacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('dueño', 'Dueño'), ('cuidador', 'Cuidador')], max_length=20)),
                ('fotoPerfil', models.URLField(blank=True, null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCuidador',
            fields=[
                ('idCuidador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_cuidador', serialize=False, to='servicios.usuario')),
                ('tipoServicio', models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería'), ('otro', 'Otro')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreMascota', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=20)),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idDueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='servicios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('idCalificación', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estrellas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idDe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to='servicios.usuario')),
                ('idParaCuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to='servicios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('idSolicitud', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipoServicio', models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería'), ('otro', 'Otro')], max_length=20)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idBloqueHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='servicios.bloquetiempo')),
                ('idCuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='servicios.usuario')),
                ('idDueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to='servicios.usuario')),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='servicios.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='bloquetiempo',
            name='idCuidador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_tiempo', to='servicios.perfilcuidador'),
        ),
        migrations.CreateModel(
            name='PrecioServicio',
            fields=[
                ('idPrecio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipoServicio', models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería'), ('otro', 'Otro')], max_length=20)),
                ('precioCOP', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idCuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_servicio', to='servicios.usuario')),
            ],
            options={
                'unique_together': {('idCuidador', 'tipoServicio')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bloquetiempo',
            unique_together={('idCuidador', 'diaSemana', 'horaInicio', 'horaFin')},
        ),
    ]
