# Generated by Django 5.2.4 on 2026-03-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_mascota_peso_mascota_raza_perfilcuidador_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
