# Generated by Django 5.2.4 on 2026-03-05 18:01

from django.db import migrations, models


def convertir_otro_a_perro(apps, schema_editor):
    Mascota = apps.get_model('servicios', 'Mascota')
    Mascota.objects.filter(tipo='otro').update(tipo='perro')


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_usuario_fotoperfil'),
    ]

    operations = [
        migrations.RunPython(convertir_otro_a_perro, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=20),
        ),
    ]
