# Generated by Django 5.2.4 on 2026-03-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_restrict_tipo_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
    ]
