# Generated by Django 5.2.4 on 2026-03-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_mascota_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='fechaFin',
            field=models.DateField(blank=True, help_text='Solo para guardería/cuidado; paseo usa solo fecha.', null=True),
        ),
    ]
