# Generated by Django 5.2.4 on 2026-03-09 16:04

from django.db import migrations, models


def mover_tipo_servicio_a_precios(apps, schema_editor):
    PerfilCuidador = apps.get_model("servicios", "PerfilCuidador")
    PrecioServicio = apps.get_model("servicios", "PrecioServicio")
    SolicitudServicio = apps.get_model("servicios", "SolicitudServicio")

    # Normaliza datos legacy antes de restringir choices.
    PrecioServicio.objects.filter(tipoServicio="otro").update(tipoServicio="paseo")
    SolicitudServicio.objects.filter(tipoServicio="otro").update(tipoServicio="paseo")

    for perfil in PerfilCuidador.objects.all():
        tipo = getattr(perfil, "tipoServicio", None) or "paseo"
        if tipo == "otro":
            tipo = "paseo"
        tarifa = max(int(getattr(perfil, "tarifaHora", 0) or 0), 1)
        PrecioServicio.objects.update_or_create(
            idCuidador=perfil.idCuidador,
            tipoServicio=tipo,
            defaults={"precioCOP": tarifa, "activo": True},
        )


def noop_reverse(apps, schema_editor):
    # No reversible: se elimina el campo legacy tipoServicio del perfil.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_add_solicitud_fecha_fin'),
    ]

    operations = [
        migrations.RunPython(mover_tipo_servicio_a_precios, noop_reverse),
        migrations.RemoveField(
            model_name='perfilcuidador',
            name='tipoServicio',
        ),
        migrations.AlterField(
            model_name='precioservicio',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería')], max_length=20),
        ),
    ]
