# Generated by Django 5.2.4 on 2026-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_multi_servicios_cuidador'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloquetiempo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bloquetiempo',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería')], default='paseo', max_length=20),
        ),
        migrations.AddField(
            model_name='precioservicio',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='bloquetiempo',
            unique_together={('idCuidador', 'tipoServicio', 'diaSemana', 'horaInicio', 'horaFin')},
        ),
    ]
