# Generated by Django 5.2.4 on 2026-03-09 17:24

import django.core.validators
import django.db.models.deletion
import uuid
from datetime import time as time_type
from django.db import migrations, models


def _time_to_minutes(t):
    return t.hour * 60 + t.minute


def _minutes_to_time(m):
    h, mn = divmod(m % (24 * 60), 60)
    return time_type(h, mn, 0)


def migrar_bloques_a_ventanas(apps, schema_editor):
    BloqueTiempo = apps.get_model('servicios', 'BloqueTiempo')
    VentanaDisponibilidad = apps.get_model('servicios', 'VentanaDisponibilidad')
    SlotDisponibilidad = apps.get_model('servicios', 'SlotDisponibilidad')
    SolicitudServicio = apps.get_model('servicios', 'SolicitudServicio')

    bloque_to_ventana = {}
    bloque_to_slots = {}

    for bloque in BloqueTiempo.objects.all():
        ventana = VentanaDisponibilidad.objects.create(
            idCuidador=bloque.idCuidador,
            tipoServicio=bloque.tipoServicio,
            diaSemana=bloque.diaSemana,
            horaInicio=bloque.horaInicio,
            horaFin=bloque.horaFin,
            duracionSlotMinutos=30,
            capacidadMaxima=5,
        )
        bloque_to_ventana[bloque.idBloque] = ventana

        hi_m = _time_to_minutes(bloque.horaInicio)
        hf_m = _time_to_minutes(bloque.horaFin)
        slots_creados = {}
        m = hi_m
        while m < hf_m:
            hora = _minutes_to_time(m)
            slot = SlotDisponibilidad.objects.create(
                idVentana=ventana,
                horaInicio=hora,
                disponible=True,
            )
            slots_creados[hora] = slot
            m += 30
        bloque_to_slots[bloque.idBloque] = slots_creados

    for sol in SolicitudServicio.objects.filter(idBloqueHorario__isnull=False).order_by('created_at'):
        bloque_id = sol.idBloqueHorario_id
        if bloque_id not in bloque_to_ventana:
            continue
        ventana = bloque_to_ventana[bloque_id]
        slots_dict = bloque_to_slots[bloque_id]
        sol.idVentana = ventana
        if slots_dict:
            orden = 1
            for hora in sorted(slots_dict.keys()):
                slot = slots_dict[hora]
                if slot.disponible:
                    sol.idSlot = slot
                    sol.horaRecogidaAsignada = hora
                    sol.ordenEnRuta = orden
                    slot.disponible = False
                    slot.save()
                    break
                orden += 1
        sol.save()


def reverse_migrar(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_solicitudservicio_estado_pago_monto_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotDisponibilidad',
            fields=[
                ('idSlot', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horaInicio', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='horaRecogidaAsignada',
            field=models.TimeField(blank=True, help_text='Asignada por el sistema según ruta', null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='ordenEnRuta',
            field=models.PositiveIntegerField(default=1, help_text='Orden en el paseo grupal'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='idBloqueHorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='servicios.bloquetiempo'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='idSlot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='servicios.slotdisponibilidad'),
        ),
        migrations.CreateModel(
            name='VentanaDisponibilidad',
            fields=[
                ('idVentana', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipoServicio', models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería')], default='paseo', max_length=20)),
                ('diaSemana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('duracionSlotMinutos', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)])),
                ('capacidadMaxima', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idCuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventanas_disponibilidad', to='servicios.perfilcuidador')),
            ],
            options={
                'unique_together': {('idCuidador', 'tipoServicio', 'diaSemana', 'horaInicio', 'horaFin')},
            },
        ),
        migrations.AddField(
            model_name='slotdisponibilidad',
            name='idVentana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='servicios.ventanadisponibilidad'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='idVentana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='servicios.ventanadisponibilidad'),
        ),
        migrations.AlterUniqueTogether(
            name='slotdisponibilidad',
            unique_together={('idVentana', 'horaInicio')},
        ),
        migrations.RunPython(migrar_bloques_a_ventanas, reverse_migrar),
    ]
