# Generated by Django 5.2.4 on 2026-03-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_ventana_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
