# Generated by Django 5.2.4 on 2026-03-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_add_cancelado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquetiempo',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ubicación del lugar de guardería', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bloquetiempo',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ubicación del lugar de guardería', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bloquetiempo',
            name='nombreLugar',
            field=models.CharField(blank=True, default='', help_text='Nombre del lugar (ej: Casa norte, Apartamento centro)', max_length=120),
        ),
    ]
