# Generated by Django 5.2.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0016_add_ubicacion_guarderia_bloque'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloquetiempo',
            unique_together={('idCuidador', 'tipoServicio', 'diaSemana', 'horaInicio', 'horaFin', 'nombreLugar')},
        ),
    ]
