# Generated by Django 5.2.4 on 2026-03-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0017_alter_bloquetiempo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ventanadisponibilidad',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bloquetiempo',
            name='precioCOP',
            field=models.IntegerField(blank=True, help_text='Precio por reunión. Si vacío, usa tarifa global.', null=True),
        ),
        migrations.AddField(
            model_name='ventanadisponibilidad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ventanadisponibilidad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ventanadisponibilidad',
            name='nombreLugar',
            field=models.CharField(blank=True, default='', help_text='Lugar del paseo (ej: Parque Norte, Zona centro)', max_length=120),
        ),
        migrations.AddField(
            model_name='ventanadisponibilidad',
            name='precioCOP',
            field=models.IntegerField(blank=True, help_text='Precio por reunión. Si vacío, usa tarifa global.', null=True),
        ),
        migrations.AlterField(
            model_name='bloquetiempo',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ubicación del lugar', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bloquetiempo',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ubicación del lugar', max_digits=9, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ventanadisponibilidad',
            unique_together={('idCuidador', 'tipoServicio', 'diaSemana', 'horaInicio', 'horaFin', 'nombreLugar')},
        ),
    ]
