# Generated by Django 5.2.4 on 2026-03-09 22:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0019_add_mensaje_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipoServicio', models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería')], max_length=20)),
                ('nombreLugar', models.CharField(blank=True, default='', max_length=120)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('diaSemana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('precioCOP', models.IntegerField(blank=True, null=True)),
                ('capacidadMaxima', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('duracionSlotMinutos', models.IntegerField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idCuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='servicios.perfilcuidador')),
            ],
            options={
                'unique_together': {('idCuidador', 'tipoServicio', 'diaSemana', 'horaInicio', 'horaFin', 'nombreLugar')},
            },
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='idEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='servicios.evento'),
        ),
        migrations.CreateModel(
            name='SlotEvento',
            fields=[
                ('idSlot', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horaInicio', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='servicios.evento')),
            ],
            options={
                'unique_together': {('idEvento', 'horaInicio')},
            },
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='idSlotEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='servicios.slotevento'),
        ),
    ]
