# Generated by Django 5.2.4 on 2026-03-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0021_migrate_bloques_ventanas_to_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioservicio',
            name='lugarEntrenamiento',
            field=models.CharField(blank=True, choices=[('cuidador', 'En mi lugar (cuidador)'), ('dueño', 'En casa del dueño')], help_text='Solo para Entrenamiento: dónde se realiza', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bloquetiempo',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería'), ('entrenamiento', 'Entrenamiento')], default='paseo', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería'), ('entrenamiento', 'Entrenamiento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='precioservicio',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería'), ('entrenamiento', 'Entrenamiento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería'), ('entrenamiento', 'Entrenamiento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ventanadisponibilidad',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería'), ('entrenamiento', 'Entrenamiento')], default='paseo', max_length=20),
        ),
    ]
