# Generated by Django 5.2.10 on 2026-03-16 17:15

import django.core.validators
from django.db import migrations, models


def _remove_entrenamiento_data(apps, schema_editor):
    model_names = [
        "SolicitudServicio",
        "Evento",
        "VentanaDisponibilidad",
        "BloqueTiempo",
        "PrecioServicio",
    ]
    for model_name in model_names:
        model = apps.get_model("servicios", model_name)
        model.objects.filter(tipoServicio="entrenamiento").delete()


def _noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0022_add_entrenamiento_lugar'),
    ]

    operations = [
        migrations.RunPython(_remove_entrenamiento_data, _noop),
        migrations.RemoveField(
            model_name='precioservicio',
            name='lugarEntrenamiento',
        ),
        migrations.AlterField(
            model_name='bloquetiempo',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería')], default='paseo', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería')], max_length=20),
        ),
        migrations.AlterField(
            model_name='precioservicio',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='radioKm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Radio de cobertura en km (solo cuidadores, 1-5 km)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='ventanadisponibilidad',
            name='tipoServicio',
            field=models.CharField(choices=[('paseo', 'Paseo'), ('guarderia', 'Guardería')], default='paseo', max_length=20),
        ),
    ]
