# Generated by Django 5.2.10 on 2026-03-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0025_usuario_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='condicionesMedicas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tamano',
            field=models.CharField(blank=True, choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacunasAlDia',
            field=models.BooleanField(default=False),
        ),
    ]
