# Generated by Django 5.2.10 on 2026-03-16

import django.core.validators
from django.db import migrations, models


def _backfill_service_location_from_usuario(apps, schema_editor):
    PerfilCuidador = apps.get_model("servicios", "PerfilCuidador")

    for perfil in PerfilCuidador.objects.select_related("idCuidador").all():
        usuario = perfil.idCuidador
        cambios = {}

        if not perfil.ciudadServicio and usuario.ciudad:
            cambios["ciudadServicio"] = usuario.ciudad
        if perfil.latitudServicio is None and usuario.latitud is not None:
            cambios["latitudServicio"] = usuario.latitud
        if perfil.longitudServicio is None and usuario.longitud is not None:
            cambios["longitudServicio"] = usuario.longitud
        if perfil.radioKmServicio is None and usuario.radioKm is not None:
            cambios["radioKmServicio"] = usuario.radioKm

        if cambios:
            PerfilCuidador.objects.filter(pk=perfil.pk).update(**cambios)


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0026_mascota_condicionesmedicas_mascota_esterilizado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilcuidador",
            name="ciudadServicio",
            field=models.CharField(blank=True, default="", help_text="Ciudad operativa usada en búsqueda de servicios", max_length=100),
        ),
        migrations.AddField(
            model_name="perfilcuidador",
            name="latitudServicio",
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Ubicación operativa para servicios", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="perfilcuidador",
            name="longitudServicio",
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Ubicación operativa para servicios", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="perfilcuidador",
            name="radioKmServicio",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Radio de cobertura operativo en km (1-5)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.RunPython(_backfill_service_location_from_usuario, migrations.RunPython.noop),
    ]
