# Generated by Django 5.2.10 on 2026-03-16

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def _cap_radio_to_3km(apps, schema_editor):
    Usuario = apps.get_model("servicios", "Usuario")
    PerfilCuidador = apps.get_model("servicios", "PerfilCuidador")

    max_radio = Decimal("3")

    Usuario.objects.filter(radioKm__gt=max_radio).update(radioKm=max_radio)
    PerfilCuidador.objects.filter(radioKmServicio__gt=max_radio).update(radioKmServicio=max_radio)


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0027_perfilcuidador_service_location_fields"),
    ]

    operations = [
        migrations.RunPython(_cap_radio_to_3km, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="usuario",
            name="radioKm",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Radio de cobertura en km (solo cuidadores, 1-3 km)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="perfilcuidador",
            name="radioKmServicio",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Radio de cobertura operativo en km (1-3)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
