# Generated by Django 5.2.10 on 2026-03-17 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0029_generalizar_calificaciones_bidireccionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idNotificacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('negocio', 'Negocio'), ('sistema', 'Sistema')], default='negocio', max_length=20)),
                ('tipoEvento', models.CharField(choices=[('nueva_reserva', 'Nueva reserva'), ('reserva_aceptada', 'Reserva aceptada'), ('reserva_rechazada', 'Reserva rechazada'), ('reserva_cancelada', 'Reserva cancelada'), ('servicio_completado', 'Servicio completado'), ('mascota_creada', 'Mascota creada'), ('mascota_editada', 'Mascota editada'), ('mascota_eliminada', 'Mascota eliminada'), ('perfil_actualizado', 'Perfil actualizado')], max_length=50)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('urlDestino', models.CharField(blank=True, default='', max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('leidaEn', models.DateTimeField(blank=True, null=True)),
                ('eliminada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idActorUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_generadas', to='servicios.usuario')),
                ('idMascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='servicios.mascota')),
                ('idParaUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to='servicios.usuario')),
                ('idSolicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='servicios.solicitudservicio')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['idParaUsuario', 'eliminada', 'leida'], name='servicios_n_idParaU_34c8b4_idx'), models.Index(fields=['idParaUsuario', 'categoria', 'eliminada'], name='servicios_n_idParaU_c2f93a_idx')],
            },
        ),
    ]
