# Generated by Django 5.2.10 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0030_notificacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacion",
            name="tipoEvento",
            field=models.CharField(
                choices=[
                    ("nueva_reserva", "Nueva reserva"),
                    ("reserva_aceptada", "Reserva aceptada"),
                    ("reserva_rechazada", "Reserva rechazada"),
                    ("reserva_cancelada", "Reserva cancelada"),
                    ("servicio_completado", "Servicio completado"),
                    ("mensaje_chat", "Mensaje de chat"),
                    ("mascota_creada", "Mascota creada"),
                    ("mascota_editada", "Mascota editada"),
                    ("mascota_eliminada", "Mascota eliminada"),
                    ("perfil_actualizado", "Perfil actualizado"),
                ],
                max_length=50,
            ),
        ),
    ]
