# Generated by Django 5.2.10 on 2026-03-18 00:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def _backfill_calificaciones_mascota(apps, schema_editor):
    Calificacion = apps.get_model('servicios', 'Calificacion')
    CalificacionMascota = apps.get_model('servicios', 'CalificacionMascota')
    SolicitudServicio = apps.get_model('servicios', 'SolicitudServicio')
    Usuario = apps.get_model('servicios', 'Usuario')

    cuidador_ids = set(Usuario.objects.filter(rol='cuidador').values_list('idUsuario', flat=True))
    if not cuidador_ids:
        return

    base = list(
        Calificacion.objects.exclude(idSolicitud=None).values(
            'idSolicitud_id',
            'idDe_id',
            'estrellas',
            'comentario',
            'fecha',
            'created_at',
        )
    )
    if not base:
        return

    solicitud_ids = {item['idSolicitud_id'] for item in base if item.get('idSolicitud_id')}
    mascota_por_solicitud = dict(
        SolicitudServicio.objects.filter(idSolicitud__in=solicitud_ids).values_list('idSolicitud', 'idMascota_id')
    )
    existentes = set(CalificacionMascota.objects.values_list('idSolicitud_id', 'idDe_id'))

    nuevas = []
    for item in base:
        solicitud_id = item.get('idSolicitud_id')
        autor_id = item.get('idDe_id')
        if not solicitud_id or not autor_id:
            continue
        if autor_id not in cuidador_ids:
            continue

        mascota_id = mascota_por_solicitud.get(solicitud_id)
        if not mascota_id:
            continue

        llave = (solicitud_id, autor_id)
        if llave in existentes:
            continue
        existentes.add(llave)

        nuevas.append(
            CalificacionMascota(
                idSolicitud_id=solicitud_id,
                idDe_id=autor_id,
                idParaMascota_id=mascota_id,
                estrellas=item.get('estrellas') or 5,
                comentario=item.get('comentario') or '',
                fecha=item.get('fecha'),
                created_at=item.get('created_at'),
            )
        )

    if nuevas:
        CalificacionMascota.objects.bulk_create(nuevas, batch_size=500)


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0031_notificacion_mensaje_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipoEvento',
            field=models.CharField(choices=[('nueva_reserva', 'Nueva reserva'), ('reserva_aceptada', 'Reserva aceptada'), ('reserva_rechazada', 'Reserva rechazada'), ('reserva_cancelada', 'Reserva cancelada'), ('servicio_completado', 'Servicio completado'), ('resena_pendiente', 'Reseña pendiente'), ('mensaje_chat', 'Mensaje de chat'), ('mascota_creada', 'Mascota creada'), ('mascota_editada', 'Mascota editada'), ('mascota_eliminada', 'Mascota eliminada'), ('perfil_actualizado', 'Perfil actualizado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('completado', 'Finalizado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='CalificacionMascota',
            fields=[
                ('idCalificacionMascota', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estrellas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idDe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_mascota_dadas', to='servicios.usuario')),
                ('idParaMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to='servicios.mascota')),
                ('idSolicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_mascota', to='servicios.solicitudservicio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idSolicitud', 'idDe'), name='uniq_calificacion_mascota_solicitud_autor')],
            },
        ),
        migrations.RunPython(_backfill_calificaciones_mascota, _noop_reverse),
    ]
