"""
Django settings for paws_walks project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-bpa1-)o^&@*gfqscdan0ck1!vbu&e=3v=zqp9-kmgt^o2h0q#h"

# SECURITY WARNING: don't run with debug turned on in production! como estamos en un entorno de desarrollo se deja habilitado el debug, pero en producción se debe deshabilitar y configurar ALLOWED_HOSTS adecuadamente.
DEBUG = True

# Estado vacío para desarrollo local, pero en producción se debe configurar con los dominios permitidos (ej: ["pawswalks.com", "www.pawswalks.com"]).
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost").split(",")


# Application definition

INSTALLED_APPS = [
    "servicios",
    "rest_framework",
    "drf_spectacular",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "paws_walks.urls"

# Templates config: se agregó el context processor para notificaciones no leídas, que estará disponible en todas las vistas.
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "servicios.context_processors.notificaciones_no_leidas",
            ],
        },
    },
]

WSGI_APPLICATION = "paws_walks.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_url = os.environ.get("DATABASE_URL", "")
if _db_url.startswith("postgresql://"):
    import urllib.parse as _up
    _p = _up.urlparse(_db_url)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _p.path.lstrip("/"),
            "USER": _p.username,
            "PASSWORD": _p.password,
            "HOST": _p.hostname,
            "PORT": _p.port or 5432,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es"

from django.utils.translation import gettext_lazy as _
LANGUAGES = [
    ("es", _("Español")),
    ("en", _("English")),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ENV_TYPE: MOCK (consola) | REAL (emails reales). Usado por NotificadorFactory.
ENV_TYPE = os.environ.get("ENV_TYPE", "MOCK")

# Microservicio de disponibilidad (Flask). Si está seteado, el Gateway lo llama vía HTTP.
# Vacío = usa el servicio interno de Django como fallback.
DISPONIBILIDAD_SERVICE_URL = os.environ.get("DISPONIBILIDAD_SERVICE_URL", "")

# API de terceros: OpenWeatherMap (Patrón Adapter).
# Obtener clave gratuita en: https://openweathermap.org/api
# Vacío = ClimaAdapterMock (datos simulados para desarrollo).
OPENWEATHER_API_KEY = os.environ.get("OPENWEATHER_API_KEY", "")

# API del equipo aliado (Patrón Adapter — consumo de servicio externo entre equipos).
# Cuando el aliado entregue su URL: setear ALIADO_API_URL en .env / docker-compose.
# Vacío = AliadoMockAdapter (datos de demostración).
ALIADO_API_URL = os.environ.get("ALIADO_API_URL", "")

# Celery — Message Broker (Redis)
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "America/Bogota"

LOGIN_URL = "/login/"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Paws & Walks API",
    "DESCRIPTION": "API REST para plataforma de cuidado de mascotas con microservicios",
    "VERSION": "2.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Cache en memoria para sesiones: reduce latencia del login (sin escribir en BD en cada request)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "OPTIONS": {"MAX_ENTRIES": 500},
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
